// Code generated by gocc; DO NOT EDIT.

package lexer

import (
	"os"
	"unicode/utf8"

	"pogo/src/token"
)

const (
	NoState    = -1
	NumStates  = 75
	NumSymbols = 97
)

type Lexer struct {
	src     []byte
	pos     int
	line    int
	column  int
	Context token.Context
}

func NewLexer(src []byte) *Lexer {
	lexer := &Lexer{
		src:     src,
		pos:     0,
		line:    1,
		column:  1,
		Context: nil,
	}
	return lexer
}

// SourceContext is a simple instance of a token.Context which
// contains the name of the source file.
type SourceContext struct {
	Filepath string
}

func (s *SourceContext) Source() string {
	return s.Filepath
}

func NewLexerFile(fpath string) (*Lexer, error) {
	src, err := os.ReadFile(fpath)
	if err != nil {
		return nil, err
	}
	lexer := NewLexer(src)
	lexer.Context = &SourceContext{Filepath: fpath}
	return lexer, nil
}

func (l *Lexer) Scan() (tok *token.Token) {
	tok = &token.Token{}
	if l.pos >= len(l.src) {
		tok.Type = token.EOF
		tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = l.pos, l.line, l.column
		tok.Pos.Context = l.Context
		return
	}
	start, startLine, startColumn, end := l.pos, l.line, l.column, 0
	tok.Type = token.INVALID
	state, rune1, size := 0, rune(-1), 0
	for state != -1 {
		if l.pos >= len(l.src) {
			rune1 = -1
		} else {
			rune1, size = utf8.DecodeRune(l.src[l.pos:])
			l.pos += size
		}

		nextState := -1
		if rune1 != -1 {
			nextState = TransTab[state](rune1)
		}
		state = nextState

		if state != -1 {

			switch rune1 {
			case '\n':
				l.line++
				l.column = 1
			case '\r':
				l.column = 1
			case '\t':
				l.column += 4
			default:
				l.column++
			}

			switch {
			case ActTab[state].Accept != -1:
				tok.Type = ActTab[state].Accept
				end = l.pos
			case ActTab[state].Ignore != "":
				start, startLine, startColumn = l.pos, l.line, l.column
				state = 0
				if start >= len(l.src) {
					tok.Type = token.EOF
				}

			}
		} else {
			if tok.Type == token.INVALID {
				end = l.pos
			}
		}
	}
	if end > start {
		l.pos = end
		tok.Lit = l.src[start:end]
	} else {
		tok.Lit = []byte{}
	}
	tok.Pos.Offset, tok.Pos.Line, tok.Pos.Column = start, startLine, startColumn
	tok.Pos.Context = l.Context

	return
}

func (l *Lexer) Reset() {
	l.pos = 0
}

/*
Lexer symbols:
0: ';'
1: ','
2: 'i'
3: 'n'
4: 't'
5: 'f'
6: 'l'
7: 'o'
8: 'a'
9: 't'
10: 'i'
11: 'f'
12: 'e'
13: 'l'
14: 's'
15: 'e'
16: 'w'
17: 'h'
18: 'i'
19: 'l'
20: 'e'
21: 'p'
22: 'r'
23: 'i'
24: 'n'
25: 't'
26: 'f'
27: 'u'
28: 'n'
29: 'c'
30: 'p'
31: 'r'
32: 'o'
33: 'g'
34: 'r'
35: 'a'
36: 'm'
37: 'b'
38: 'e'
39: 'g'
40: 'i'
41: 'n'
42: 'e'
43: 'n'
44: 'd'
45: 'v'
46: 'a'
47: 'r'
48: 's'
49: '='
50: '='
51: '!'
52: '='
53: '<'
54: '>'
55: '+'
56: '-'
57: '*'
58: '/'
59: '='
60: ':'
61: '{'
62: '}'
63: '('
64: ')'
65: '0'
66: '.'
67: '_'
68: '`'
69: '`'
70: '\'
71: 'n'
72: '\'
73: 'r'
74: '\'
75: 't'
76: '"'
77: '\'
78: '"'
79: '"'
80: '/'
81: '/'
82: '\n'
83: '/'
84: '*'
85: '*'
86: '*'
87: '/'
88: ' '
89: '\t'
90: '\n'
91: '\r'
92: '1'-'9'
93: 'a'-'z'
94: 'A'-'Z'
95: '0'-'9'
96: .
*/
